### ISSUE TITLE
Clarification of usage

### ISSUE THREAD

**Issue by robertklep** [vankasteelj/tvdbapi#2]
I'm wondering if the following should work:
```
 await tvdb.login({ pin : MY_PIN });
 const results = await tvdb.search({ q : QUERY });
```

I'm getting a 400 error on the search because the authentication token isn't being passed along. I fixed [this line](https://github.com/vankasteelj/tvdbapi/blob/23bbd600b2c12146873169c61d9d948350a123fa/tvdb.js#L128) to the following to get it working:
```
return this.login(this._authentication).then(…)
```

But I wonder if I'm just missing something.

**Comment by vankasteelj** [comment]
Hi, I've missed your issue. 

You need to have response to your 'login' before you can 'search'. I'm not an async/await user so idk, but the best usecase would be:
```js
tvdb.login({pin: MY_PIN}).then(() => {
  retrun tvdb.search({q: QUERY})
}).then((searchResults) => { ... }).catch(console.error)
```

I don't see how your correction changes anything, but I've added it just in case i'm missing something with the await/async that I'm not that familiar with, as it works with promises as well
